apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s5wesley-do-it-yourself
  namespace: s5wesley-argocd
spec:
  project: default

  source:
    repoURL: https://github.com/DEL-ORG/s5wesley-do-it-yourself-automation.git
    targetRevision: HEAD
    path: chart/templates
  destination: 
    server: https://kubernetes.default.svc
    namespace: wesley-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true